### ISSUE TITLE
one other small thing

### ISSUE THREAD

**Issue by rcrooks** [IKKI2000/IKKI-VSCode-Dark-Theme#2]
for some reason it shows up in the Light Themes instead of Dark. Assume that's something in the package.json, but haven't checked.
<img width="583" alt="2020-07-29_13-19-24" src="https://user-images.githubusercontent.com/619617/88832258-8daa2f00-d19e-11ea-8772-54efbc104ff5.png">

**Comment by IKKI2000** [comment]
@rcrooks Thank you very much for your attention! Please don't worry. This detail has been fixed in the latest v1.0.0 today. Please update and enjoy it.
