### ISSUE TITLE
Background color gap when not in full-screen mode

### ISSUE THREAD

**Issue by Alexn117** [IKKI2000/IKKI-VSCode-Dark-Theme#3]
Not sure if this is by design, as I've seen the issue with other themes as well. The background color of the editor contains a gap with a darker color behind, when not in full-screen mode on macOS. This does not happen with the light version of the theme.

![Screen Shot 2020-07-30 at 1 28 17 PM](https://user-images.githubusercontent.com/29024614/88955452-f1e5f500-d269-11ea-85e9-bbb7d531a23e.png)

**Comment by IKKI2000** [comment]
@Alexn117 I don't have macOS to reproduce this issue. No matter whether it is a light theme or a dark theme in Windows, this doesn't happen. If this is also the case with other dark themes, I tend to think that this is a style bug of VSCode itself, which cannot be repaired by the theme setting.

**Comment by Alexn117** [comment]
You're right, I did some research and it's a known bug. There's an easy fix though. I did this:

1. View > Command Palette...
2. Search for **“Configure Runtime Arguments”** and select it.
3. Comment out the last line: `// "disable-color-correct-rendering": true`
